# golangci-lint configuration for sdk
# https://golangci-lint.run/

run:
  timeout: 5m
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Security
    - gosec
    # Bugs
    - staticcheck
    - govet
    - errcheck
    - ineffassign
    - typecheck
    # Style
    - gofmt
    - goimports
    - misspell
    # Complexity
    - gocyclo
    - funlen

  disable:
    - depguard
    - prealloc  # Disable prealloc - too noisy for CLI code

linters-settings:
  gosec:
    excludes:
      - G104  # Audit errors not checked
      - G304  # File path provided as taint input
    config:
      G301: "0750"
      G302: "0640"
      G306: "0640"

  funlen:
    lines: 200
    statements: 100

  gocyclo:
    min-complexity: 50  # Increased for complex CLI code

  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
    - tmp
    - examples

  exclude-rules:
    # Exclude test files from some linters
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - funlen

    # Exclude examples from most linters
    - path: examples/
      linters:
        - gosec
        - errcheck
        - funlen

    # Exclude main.go from complexity checks (CLI entry point)
    - path: cmd/.*main\.go
      linters:
        - gocyclo
        - funlen

  max-issues-per-linter: 50
  max-same-issues: 10
